
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Kaua33500476
 */
public class Carro extends javax.swing.JFrame {

    float velocidade = 0; //acumulador de velocidade
    float gasolina; //indicador de gasolina
    String ligado; 
    String km = "Km";
    String L = "L";
    Timer tempo = new Timer(); //utilizar ele para reduzir e aumentar; colocando no escopo global, consigo cancelar quando necessário

    /**
     * Creates new form Carro
     */
    public Carro() {
        initComponents();
        ligado = "Não";
        textArea.setText("Ligado: " + ligado + "\nGasolina: " + gasolina + L + "\nVelocidade: " + velocidade + km );
        gasolina = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLigar = new javax.swing.JButton();
        btAbastecer = new javax.swing.JButton();
        btAumentar = new javax.swing.JButton();
        btReduzir = new javax.swing.JButton();
        btDesligar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btLigar.setText("Ligar");
        btLigar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLigarMouseClicked(evt);
            }
        });

        btAbastecer.setText("Abastacer");
        btAbastecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAbastecerMouseClicked(evt);
            }
        });

        btAumentar.setText("Aumentar_Velocidade");
        btAumentar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAumentarMouseClicked(evt);
            }
        });

        btReduzir.setText("Reduzir_Velocidade");
        btReduzir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btReduzirMouseClicked(evt);
            }
        });

        btDesligar.setText("Desligar");
        btDesligar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDesligarMouseClicked(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAumentar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btReduzir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLigar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbastecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDesligar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLigar)
                        .addGap(18, 18, 18)
                        .addComponent(btAbastecer)
                        .addGap(16, 16, 16)
                        .addComponent(btAumentar)
                        .addGap(12, 12, 12)
                        .addComponent(btReduzir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDesligar))
                    .addComponent(jScrollPane1))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAbastecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAbastecerMouseClicked
        //Primeiro pedir para ele abastecer para depois ligar
        String input = JOptionPane.showInputDialog(null, "Abastacer quanto?:", "Gasolina", JOptionPane.QUESTION_MESSAGE);
        gasolina += Integer.parseInt(input);
        textArea.setText("Ligado: " + ligado + "\nGasolina: " + gasolina + L + "\nVelocidade: " + velocidade + km);

    }//GEN-LAST:event_btAbastecerMouseClicked

    private void btLigarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLigarMouseClicked
        //Após abastacer, pode ligar
        if (gasolina > 0) {
            ligado = "Sim";
            textArea.setText("Ligado: " + ligado + "\nGasolina: " + gasolina + L + "\nVelocidade: " + velocidade + km);
        } else {
            JOptionPane.showMessageDialog(null, "Abastacer primeiro");
        }
    }//GEN-LAST:event_btLigarMouseClicked

    private void btAumentarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAumentarMouseClicked
         tempo.cancel(); // Cancela qualquer timer existente.
         tempo = new Timer(); // Cria um novo timer após ser cancelado pelo reduzir_Velocidade;
         
        if (gasolina > 0 && ligado.equals("Sim") || velocidade < 150) {
            TimerTask tarefa = new TimerTask() {
                @Override
                public void run() {
                    if (velocidade < 150) {
                        velocidade += 10;
                        textArea.setText("Ligado: " + ligado + "\nGasolina: " + gasolina + L + "\nVelocidade: " + velocidade + km);
                    } else if (velocidade >= 150) {
                        JOptionPane.showMessageDialog(null, "Limite de velocidade atingido");
                        tempo.cancel();

                    }
                }

            };
            tempo.scheduleAtFixedRate(tarefa, 0, 2000);
        } else {
            JOptionPane.showMessageDialog(null, "Tem que ligar primeiro");

        }
    }//GEN-LAST:event_btAumentarMouseClicked

    private void btReduzirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReduzirMouseClicked
        if (velocidade > 0) {
            tempo.cancel();
            velocidade = velocidade - 10;
            textArea.setText("Ligado: " + ligado + "\nGasolina: " + gasolina + L + "\nVelocidade: " + velocidade + km);
        } else {
            JOptionPane.showMessageDialog(null, "Carro parado");
        }
    }//GEN-LAST:event_btReduzirMouseClicked

    private void btDesligarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesligarMouseClicked
        if(ligado.equals("Sim") && velocidade > 0){
            JOptionPane.showMessageDialog(null,"Carro está ligado");
        } 
        else{
            JOptionPane.showMessageDialog(null,"Carro desligado");
            ligado = "Não";
            textArea.setText("Ligado: " + ligado + "\nGasolina: " + gasolina + L + "\nVelocidade: " + velocidade + km);
          
        } 
    }//GEN-LAST:event_btDesligarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbastecer;
    private javax.swing.JButton btAumentar;
    private javax.swing.JButton btDesligar;
    private javax.swing.JButton btLigar;
    private javax.swing.JButton btReduzir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
